In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("04_data/products.parquet")

In [7]:
df2 = pd.read_parquet("04_data/stores.parquet")

In [10]:
df3 = pd.read_parquet("04_data/transaction_lines.parquet")

In [17]:
df4 = pd.read_parquet("04_data/transactions.parquet")

In [14]:
df.columns

Index(['id', 'base_product_id', 'category', 'name', 'price', 'popularity',
       'valid_from', 'valid_to', 'sold_by_weight', 'weight', 'age_restricted',
       'is_scannable'],
      dtype='object')

In [15]:
df2.columns

Index(['id', 'opening_date', 'location', 'state', 'urbanization',
       'sco_introduction'],
      dtype='object')

In [16]:
df3.columns

Index(['id', 'transaction_id', 'product_id', 'timestamp', 'pieces_or_weight',
       'sales_price', 'was_voided', 'camera_product_similar',
       'camera_certainty'],
      dtype='object')

In [18]:
df4.columns

Index(['id', 'store_id', 'cash_desk', 'transaction_start', 'transaction_end',
       'total_amount', 'n_lines', 'payment_medium', 'customer_feedback',
       'damage', 'label'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               23896 non-null  object
 1   base_product_id  23896 non-null  object
 2   category         23896 non-null  object
 3   name             23896 non-null  object
 4   price            23896 non-null  float64
 5   popularity       23896 non-null  float64
 6   valid_from       23896 non-null  object
 7   valid_to         18476 non-null  object
 8   sold_by_weight   23896 non-null  bool
 9   weight           19131 non-null  float64
 10  age_restricted   23896 non-null  bool
 11  is_scannable     23896 non-null  bool
dtypes: bool(3), float64(3), object(6)
memory usage: 1.7+ MB

In [20]:
df.head()

,id,base_product_id,category,name,price,popularity,valid_from,valid_to,sold_by_weight,weight,age_restricted,is_scannable
0,b'\x00\x02>\xb8Z\xaeE\xaa\xb3\x13\xbb\xf4\x00\...,"b'\x97IP\x16D\xa5A\xee\xb3\n\xb8""\xa1];\xdf'",FROZEN_GOODS,Fish Sticks,5.99,0.060359,2022-01-30,2023-10-09,False,1.99,False,True
1,b'\x00\x02\xa9!\xff\x17O%\x83\xc4 \xfa\xb9\xba...,b'\x00\x02\xa9!\xff\x17O%\x83\xc4 \xfa\xb9\xba...,BEVERAGES,Soda,0.49,0.181330,2014-09-23,None,False,1.00,False,True
2,b'\x00\x06r\x91)\xaeF\xa7\x88\x96\xf9\x95v\x9c...,"b'\x96=Bom\n@\xe3\x9bY""m\x840\xd9\x88'",PERSONAL_CARE,Deodorant,2.79,0.114471,2017-12-10,2022-09-29,False,0.53,False,True
3,b'\x00\x08\x004\x04)NK\xb1A\xdeubd-\x14',b'\x1ct\xd8\x8b\x89\xceG\xc4\xb3\x9e\xae\x04\x...,ALCOHOL,Vodka,16.49,0.007391,2016-10-15,2018-08-19,False,0.50,True,True
4,b'\x00\n \xe3e\x90O\xa0\xad\xfb\x01>r9\x1b\x0e',b'\x00\n \xe3e\x90O\xa0\xad\xfb\x01>r9\x1b\x0e',PERSONAL_CARE,Toothpaste,1.49,0.148460,2011-02-18,2016-04-27,False,0.39,False,True

In [24]:
df.tail()

,id,base_product_id,category,name,price,popularity,valid_from,valid_to,sold_by_weight,weight,age_restricted,is_scannable
23891,b'\xff\xf7\x04L\x17\xefF\xbd\x81\xbc\x9b\x9a\x...,b'\xff\xf7\x04L\x17\xefF\xbd\x81\xbc\x9b\x9a\x...,FROZEN_GOODS,Vegetables,6.99,0.049418,2022-06-28,2022-08-17,False,0.80,False,True
23892,"b""\xff\xf7V\xd7\x02'@7\xad\t,\x04\xd8U\xb17""",b'\xf4$\x02D&tF\x0e\x9aS\xb2\xf3\x8bw1\x11',CONVENIENCE,Sushi,3.99,0.090046,2024-04-27,None,False,0.52,False,True
23893,b'\xff\xf7\xf64\xfd\\D\xcb\xa9\xc3\x9b\x98\xa0...,b'\xff\xf7\xf64\xfd\\D\xcb\xa9\xc3\x9b\x98\xa0...,HOUSEHOLD,Trash Bags,1.39,0.151459,2011-01-17,2020-04-06,False,2.34,False,True
23894,b'\xff\xfb\x0f\x05f\xe6D\xe5\xb3\x91\x91\xeb\x...,b'\xba\xb1\xd6-}\x90A1\x8b\xbbOOU\x9f\xd8{',FRUITS_VEGETABLES,Carrot,3.99,0.090046,2023-04-25,2025-07-20,True,NaN,False,False
23895,b'\xff\xffK\x12\xefLH\x0b\x96\x95\x1d\xf8\xa0+...,b'B2\xa0\xb0\xc1%Aa\xaej\xb1\xedF8\x84\x00',FROZEN_GOODS,Ice Cream,4.79,0.076732,2017-08-26,2019-09-05,False,1.01,False,True

In [21]:
df.value_counts("category")

category
FRUITS_VEGETABLES           3863
LONG_SHELF_LIFE             3647
DAIRY                       2291
FROZEN_GOODS                2260
FRUITS_VEGETABLES_PIECES    1993
ALCOHOL                     1984
CONVENIENCE                 1693
PERSONAL_CARE               1648
SNACKS                      1254
HOUSEHOLD                   1146
TOBACCO                      902
LIMITED_TIME_OFFERS          461
BEVERAGES                    457
BAKERY                       297
Name: count, dtype: int64

In [22]:
df.value_counts("base_product_id")

base_product_id
b']\xc1Mm\xb7\xd3H:\x89\xc1\x89#\xdak\x03\xf9'                   18
b'\xadKm{5\xb1D\x15\xb5\xd6\x96\xfe\xc6\xdb\\f'                  17
b'\xbd\x1f%\x98`\xb9A\x81\xb2\xb5\xbb\xfa\xe9\xdf\x14\xfb'       16
b'o\xfd\xc4\xc6\x80\xbdJ\x9e\x905\xbc\xa7\xd2\xa5v\xe2'          16
b'D\xe7\xfdV\xc4kH\x9e\x9e"\xc0\xd6\xde\x10\xc1F'                15
                                                                 ..
b'\xff\xc52\xfcx\xacNl\xa4Z\xf3G\xdew\xadh'                       1
b'\xff#OC8mE*\x92\x1f\xb95V\x01\xa3\x0c'                          1
b'\xff\x1c\xb8\xdd6\x8dA\xd8\x8e\xda\xd7\xd2\x8b\x7f\x86\xe0'     1
b'\xff\x11\xfcH\xa6oA\xf5\x9e\x8c\xb9WZ.=\x98'                    1
b"\xff\x0c\xa7:\x12'@b\x87'\x0f=\xe5uP\x81"                       1
Name: count, Length: 9241, dtype: int64

In [23]:
df.describe()

              price    popularity        weight
count  23896.000000  2.389600e+04  19131.000000
mean       5.965933  1.009589e-01      0.945091
std       22.484213  5.043946e-02      0.855601
min        0.190000  2.944422e-57      0.100000
25%        1.790000  6.282276e-02      0.450000
50%        2.990000  1.099821e-01      0.750000
75%        5.790000  1.398146e-01      1.250000
max      642.790000  1.925426e-01     12.550000

In [25]:
df2.head()

,id,opening_date,location,state,urbanization,sco_introduction
0,b'\xcf\x1c@9i\xf6O\x9f\xb2p`\xe2\xe6!j\xbd',1990-07-01,Jena,Thüringen,0,2022-03-21
1,b'\x14\x80\x1d\x0f\xe2\xcbI\xea\x9b\xf1\x0c\\\...,1990-09-06,Nürnberg,Bayern,0,2022-02-13
2,"b'\x1b""Be\xb2\x8aKo\xa5eB\x9a\x86\x87\xdf\xc6'",1990-11-17,Dresden,Sachsen,0,2022-03-24
3,b'\xbfL\xc3\x06gYA\xa3\xaa\xf1\x8f]\xe5\xe6\x9ew',1991-07-13,Köln,Nordrhein-Westfalen,0,2022-02-19
4,b'R\xedR\xc8\xdc7F\x95\x87\x87\x85\xdff\xc6/o',1991-07-19,Leipzig,Sachsen,0,2022-03-18

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                50 non-null     object
 1   opening_date      50 non-null     object
 2   location          50 non-null     object
 3   state             50 non-null     object
 4   urbanization      50 non-null     int64
 5   sco_introduction  50 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.5+ KB

In [29]:
df2.describe()

       urbanization
count     50.000000
mean       0.460000
std        0.676425
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        2.000000

In [31]:
df2.value_counts("urbanization")

urbanization
0    32
1    13
2     5
Name: count, dtype: int64

In [37]:
df2.groupby("urbanization")["location"].value_counts()

urbanization  location
0             Berlin        4
              Hamburg       3
              Bonn          2
              Dresden       2
              Duisburg      2
              Köln          2
              Mannheim      2
              München       2
              Nürnberg      2
              Stuttgart     2
              Bielefeld     1
              Bochum        1
              Düsseldorf    1
              Essen         1
              Jena          1
              Krefeld       1
              Leipzig       1
              Ulm           1
              Wiesbaden     1
1             Ingolstadt    2
              Potsdam       2
              Chemnitz      1
              Hamburg       1
              Heilbronn     1
              Jena          1
              Karlsruhe     1
              Pforzheim     1
              Solingen      1
              Ulm           1
              Wiesbaden     1
2             Duisburg      1
              Erlangen      1
              Ingolstadt    1
              Mainz         1
              Regensburg    1
Name: count, dtype: int64

In [36]:
df2.value_counts("state")

state
Nordrhein-Westfalen    13
Baden-Württemberg       9
Bayern                  9
Berlin                  4
Sachsen                 4
Hamburg                 4
Hessen                  2
Brandenburg             2
Thüringen               2
Rheinland-Pfalz         1
Name: count, dtype: int64

In [38]:
df2.columns

Index(['id', 'opening_date', 'location', 'state', 'urbanization',
       'sco_introduction'],
      dtype='object')

In [39]:
df3.head()

,id,transaction_id,product_id,timestamp,pieces_or_weight,sales_price,was_voided,camera_product_similar,camera_certainty
0,1,b'j\xc8\x10\x0c\x13\xd1Gm\xab\xeeU<MmGk',b'+\xe0/\xf0\xb7\xd0F\xab\x85\xc9 \xa1\xaa\xc3...,2022-02-07 08:01:02.881395,1.000,0.49,False,False,0.281858
1,2,b'j\xc8\x10\x0c\x13\xd1Gm\xab\xeeU<MmGk',b'\xdf\x02\xc7<.4DV\x89R\x0f\x90)\x07tG',2022-02-07 08:01:04.559786,1.000,7.00,False,True,0.286228
2,3,b'j\xc8\x10\x0c\x13\xd1Gm\xab\xeeU<MmGk',"b""yeC\xf79eF\x9e\xa9\x84\xb1'\x19*\x91\x8a""",2022-02-07 08:01:04.890541,1.000,2.19,False,False,0.319623
3,4,b'j\xc8\x10\x0c\x13\xd1Gm\xab\xeeU<MmGk',b'\xa5\x82\xd32:\xb7D\xce\xa1\x0c\xed\x9b\xd3\...,2022-02-07 08:01:14.959243,1.609,2.88,False,None,NaN
4,5,b'j\xc8\x10\x0c\x13\xd1Gm\xab\xeeU<MmGk',b'\xe5\x149\x83\xbe\xbbFA\x88\x07LID\xc1\xef`',2022-02-07 08:01:15.653082,1.000,3.79,False,False,0.295411

In [41]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20092938 entries, 0 to 20092937
Data columns (total 9 columns):
 #   Column                  Dtype
---  ------                  -----
 0   id                      int64
 1   transaction_id          object
 2   product_id              object
 3   timestamp               datetime64[us]
 4   pieces_or_weight        float64
 5   sales_price             float64
 6   was_voided              bool
 7   camera_product_similar  object
 8   camera_certainty        float64
dtypes: bool(1), datetime64[us](1), float64(3), int64(1), object(3)
memory usage: 1.2+ GB

In [42]:
df3.tail()

,id,transaction_id,product_id,timestamp,pieces_or_weight,sales_price,was_voided,camera_product_similar,camera_certainty
20092933,57,b']\x93X\xc2s\xb3E\x89\xa95&\xd7\xf5\x11\xfc\x9b',b'P\xa3\x87K\t\xa5N\xee\xadS\x1d\xfe\xb4W\xd8&',2023-12-30 21:02:21.953361,1.000,2.19,False,True,0.920444
20092934,30,b'C\xf2)7\xe2^In\x84#X]\xcc\x1cg\xf3',b'\x16$\xcb\x1f\xbd\xf7L\x83\xac!\x0b\xed\xdd\...,2023-12-30 21:02:23.590532,1.000,3.79,False,False,0.498251
20092935,58,b']\x93X\xc2s\xb3E\x89\xa95&\xd7\xf5\x11\xfc\x9b',b'\xed\xe4\xf65e]C\x95\xb0\xeeX\x05\x00\x92\x8...,2023-12-30 21:02:23.832211,1.000,1.19,False,True,0.908721
20092936,31,b'C\xf2)7\xe2^In\x84#X]\xcc\x1cg\xf3',b'\x99\x82t\x0c\xfc\xdbI\xea\x88d-\xaf\xebS(\xb5',2023-12-30 21:02:30.079962,1.000,2.39,False,True,0.974090
20092937,32,b'C\xf2)7\xe2^In\x84#X]\xcc\x1cg\xf3',b'\x03a\x97zj~K\xf7\xab\xe1\x0f\x10d\xc8\xb7\x10',2023-12-30 21:02:34.773198,1.536,17.65,False,None,NaN

In [44]:
df3.columns

Index(['id', 'transaction_id', 'product_id', 'timestamp', 'pieces_or_weight',
       'sales_price', 'was_voided', 'camera_product_similar',
       'camera_certainty'],
      dtype='object')

In [49]:
df4.head(10)

,id,store_id,cash_desk,transaction_start,transaction_end,total_amount,n_lines,payment_medium,customer_feedback,damage,label
0,b'j\xc8\x10\x0c\x13\xd1Gm\xab\xeeU<MmGk',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",101,2022-02-07 08:00:54,2022-02-07 08:01:37.038826,21.02,8,credit_card,NaN,NaN,-1
1,b'\x1b&\xb5TT\x9cK\xc6\xa9\x82*C)\xc0\xe2\x1d',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",102,2022-02-07 08:02:18,2022-02-07 08:05:59.234066,87.64,40,credit_card,NaN,NaN,-1
2,b'\xd5\x9b\x17\x9eL\x07Dg\x8f\xf9\xed\xbb)\xa1...,"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",103,2022-02-07 08:03:42,2022-02-07 08:03:56.348644,2.18,2,credit_card,NaN,NaN,-1
3,"b'S\xa3\x9d\xb5i\x11A\xc4\x9f\xa87v\xed""\x8f\x9d'","b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",104,2022-02-07 08:04:24,2022-02-07 08:05:11.478324,16.74,9,credit_card,NaN,NaN,-1
4,b'v;U<HhJ\t\xab\xc1\xc6fow\xa3\x9d',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",101,2022-02-07 08:09:18,2022-02-07 08:09:55.472995,14.21,8,credit_card,NaN,NaN,-1
5,b'\xd7O\xdf\xe3\x8c\xcbDO\x89\x9d?#3\x95\x9e\xbb',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",103,2022-02-07 08:09:39,2022-02-07 08:10:00.138997,4.17,2,credit_card,NaN,NaN,-1
6,b'q\xa2l\xb2\x80\x91Mc\xb5Xq\x02+\xea\x13\xb6',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",104,2022-02-07 08:09:39,2022-02-07 08:10:36.038755,20.77,10,credit_card,NaN,NaN,-1
7,b'\xb2\xaa\\\x0f\xa0HHE\x96[\xcc\xcc\x05;M\xb9',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",102,2022-02-07 08:17:21,2022-02-07 08:17:56.618100,11.92,5,credit_card,NaN,NaN,-1
8,b'c\xbf\xd8\xda[\xd3E\x13\xa1\x87da\xc1\xad\xd...,"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",101,2022-02-07 08:18:03,2022-02-07 08:20:25.043144,63.95,25,credit_card,NaN,NaN,-1
9,b'\x05r\xd8\xaa\x99%M\x1b\x8e$2i\x1c\xe73\xcb',"b'r\xec\xa2\t\xd3\xfdG\x0b\xb7J\xda\x8b\xc2p""\...",103,2022-02-07 08:21:54,2022-02-07 08:23:36.256545,41.36,14,credit_card,NaN,NaN,-1

In [46]:
df4["payment_medium"].value_counts()

payment_medium
credit_card    1107078
cash            757038
Name: count, dtype: int64

In [47]:
df4.isna().sum()

id                         0
store_id                   0
cash_desk                  0
transaction_start          0
transaction_end            0
total_amount               0
n_lines                    0
payment_medium             0
customer_feedback    1730614
damage               1856390
label                      0
dtype: int64

In [48]:
df4["n_lines"].value_counts()

n_lines
2      208228
3      167526
4      142170
1      135106
5      122935
        ...
159         1
187         1
173         1
158         1
149         1
Name: count, Length: 163, dtype: int64

In [51]:
df4["cash_desk"].value_counts()

cash_desk
101    467877
102    466476
103    465493
104    464270
Name: count, dtype: int64

In [52]:
df4["label"].value_counts()

label
-1    1678031
 0     178359
 1       7726
Name: count, dtype: int64